# Generated by Django 5.2.1 on 2025-07-15 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_clientemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='created',
        ),
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='same_images', to='apps.gallery', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Gallery Additional Image',
                'verbose_name_plural': 'Gallery Additional Images',
            },
        ),
    ]
