# Generated by Django 5.2.1 on 2026-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_gallery_created_gallerygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetranslation',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
