# Generated by Django 5.2.1 on 2026-10-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_seed_uzbek_service_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service-works/%Y/%m/%d/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='apps.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Work',
                'verbose_name_plural': 'Service Works',
                'ordering': ['order', 'id'],
            },
        ),
    ]
