# Generated by Django 5.2.1 on 2026-10-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_servicework'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='gallerygroup',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
    ]
