# Generated by Django 5.2.1 on 2026-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_gallery_thumbnail_gallerygroup_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='partner',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
    ]
