# Generated by Django 5.2.1 on 2026-10-03 09:05

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_banner_thumbnail_partner_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to generate it from the English title.', unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to='projects/%Y/%m/%d', verbose_name='Cover')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year')),
                ('category', models.CharField(choices=[('hotel', 'Hotel'), ('museum', 'Museum'), ('outdoor', 'Outdoor'), ('interior', 'Interior'), ('corporate', 'Corporate'), ('facade', 'Facade')], default='outdoor', max_length=20, verbose_name='Category')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d')),
                ('image', models.ImageField(upload_to='project-photos/%Y/%m/%d', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apps.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Location')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('materials', models.TextField(blank=True, default='', verbose_name='Materials')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='apps.project')),
            ],
            options={
                'verbose_name': 'Project Translation',
                'db_table': 'apps_project_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
