# Generated by Django 5.2.1 on 2026-10-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_lowercase_project_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/%d'),
        ),
    ]
