# Generated by Django 5.2.1 on 2026-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_seed_service_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, default='image', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, help_text='MP4/MOV/WEBM, up to 120 seconds, up to 100 MB. The poster is created automatically.', null=True, upload_to='videos/%Y/%m/%d', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='gallerygroup',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gallerygroup',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, default='image', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='gallerygroup',
            name='video',
            field=models.FileField(blank=True, help_text='MP4/MOV/WEBM, up to 120 seconds, up to 100 MB. The poster is created automatically.', null=True, upload_to='videos/%Y/%m/%d', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, default='image', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='video',
            field=models.FileField(blank=True, help_text='MP4/MOV/WEBM, up to 120 seconds, up to 100 MB. The poster is created automatically.', null=True, upload_to='videos/%Y/%m/%d', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image or a video. For a video the poster is created automatically; upload an image only to use your own poster.', upload_to='images/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='gallerygroup',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image or a video. For a video the poster is created automatically; upload an image only to use your own poster.', upload_to='images/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image or a video. For a video the poster is created automatically; upload an image only to use your own poster.', upload_to='project-photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
