# Generated by Django 5.2.1 on 2026-10-07 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_fix_service_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9\\s+\\-()]*$', 'Enter a valid phone number.')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Subject'),
        ),
    ]
