# Generated by Django 5.2.1 on 2026-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_dedupe_client_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemail',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
