# Generated by Django 5.2.1 on 2026-10-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_client_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, help_text='Instagram or YouTube link (for example https://www.instagram.com/reel/XXXX/). For Instagram also upload a poster image. If a video file is uploaded too, the file takes priority.', max_length=300, verbose_name='Video link'),
        ),
        migrations.AddField(
            model_name='gallerygroup',
            name='video_url',
            field=models.URLField(blank=True, help_text='Instagram or YouTube link (for example https://www.instagram.com/reel/XXXX/). For Instagram also upload a poster image. If a video file is uploaded too, the file takes priority.', max_length=300, verbose_name='Video link'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='video_url',
            field=models.URLField(blank=True, help_text='Instagram or YouTube link (for example https://www.instagram.com/reel/XXXX/). For Instagram also upload a poster image. If a video file is uploaded too, the file takes priority.', max_length=300, verbose_name='Video link'),
        ),
    ]
